#include "Vspi_master_controller.h"    // generated by Verilator
#include "verilated.h"
#include "verilated_vcd_c.h"
#include <iostream>
#include <cstdint>

void tick(int32_t tick_val, Vspi_master_controller *dut, VerilatedVcdC* tfp);

int main(int argc, char **argv, char **env) {
    Verilated::commandArgs(argc, argv);
    Vspi_master_controller *dut = new Vspi_master_controller;

    // VCD waveform dump (optional)
    VerilatedVcdC* tfp = new VerilatedVcdC;
    Verilated::traceEverOn(true);
    dut->trace(tfp, 99);
    tfp->open("waveform.vcd");

    tick(5, dut, tfp);
    dut->rstn = 0;
    tick(5, dut, tfp);
    dut->rstn = 1;

    tick(50, dut, tfp);

    // Finish
    dut->final();
    tfp->close();
    delete dut;
    return 0;
}

vluint64_t sim_time = 0;

void tick(int32_t tick_val, Vspi_master_controller *dut, VerilatedVcdC* tfp) {
    for (int i = 0; i < tick_val; i++) {
        dut->clk = 0;
        dut->eval();
        tfp->dump(sim_time++);

        dut->clk = 1;
        dut->eval();
        tfp->dump(sim_time++);
    }
}